### ISSUE TITLE
Remote data collection and forwarding 

### ISSUE THREAD

**Issue by gedw99** [anyshake/explorer#4]
hey @bclswl0827 

thanks for this hardware . It looks like what I need for an EU Science project I am working with .

the next branch looks good.

https://github.com/simpleiot/simpleiot Is what I use for field sensors  like the hardware in question. It’s based on nats.

 So when you have hundreds of sensors you can ensure data gets to your servers and it will use a store and forward pattern . I don’t know if you’re only sending when abnormal data occurs on the hardware ? 

I have used Lora which is perfectly fine for seismic data at the baud rates your using. 

Lora nodes are run by most Universities too to allow large spans of geography . 

it’s low power and hardware that works with tinygo exists. 

Your base board is an arduino , and so tinygo will do nats works fine there.

https://tinygo.org/docs/reference/microcontrollers/lorae5/

https://pkg.go.dev/tinygo.org/x/drivers/lora

https://github.com/hybridgroup/tinyglobo has code but links to the global Things Network for Lora.

I was also wondering if you have designed for firmware updates yet ?  Nats is often used to do that too .

if any of this sounds useful let me know ..

**Comment by bclswl0827** [comment]
If you have read the code of AnyShake Explorer (master or next branch), you will find that whenever the data collected by the sensor is sent to AnyShake Observer, instead of "only sending when abnormal data occurs", this is because the AnyShake Observer need to stream and archive data in a timely manner so that users can access it at any time.

LoRa is theoretically possible, but after my testing (I'm using [AS32-DTU-100](http://en.ashining.com/product_view.aspx?t=143&cid=116)), at a sampling rate of 100 sps, the actual sampling rate calculated by AnyShake Observer is only 80 sps. I would rather recommend transmitting data wirelessly via TCP over 4G network, otherwise, RS485 would be a better choice.

You mentioned firmware updates, if I understand correctly, do you mean OTA?

**Comment by bclswl0827** [comment]
> Regarding the topic of OTA updates, yeah I was wondering how your not bricking the device if your doing embedded hardware ?

Regarding OTA, I'm currently using STM32. To prevent bricking, one of my ideas is to burn the firmware by an extra ESP32 / ESP8266. This may increase the cost, but it's effective.

See https://github.com/ESP32-Musings/OTA_update_STM32_using_ESP32
